# Generated by Django 3.2 on 2022-09-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='total',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
