# Generated by Django 3.2 on 2022-09-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_usersession_loggedout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='loggedout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
